### ISSUE TITLE
realpath 1.0.1 claims to be 1.0.0

### ISSUE THREAD

**Issue by ryandesign** [user454322/realpath#1]
```
$ /opt/local/bin/realpath -v
1.0.0
```
```
$ port provides /opt/local/bin/realpath
/opt/local/bin/realpath is provided by: realpath
```
```
$ port -v installed realpath
The following ports are currently installed:
  realpath @1.0.1_0+universal (active) platform='darwin 17' archs='i386 x86_64' date='2020-10-16T11:24:39-0500'
```

**Comment by user454322** [comment]
Thank you @ryandesign.

I'll check this

**Comment by user454322** [comment]
The issue has been fixed in v1.0.2.

See https://github.com/user454322/realpath/commit/1fa9e4929171bb55bf0c23b725d2659f6cfac9d8

**Comment by user454322** [comment]
This ticket will be closed once 1.0.2 is in MacPorts

**Comment by ryandesign** [comment]
Thanks, update proposed in https://github.com/macports/macports-ports/pull/12036

**Comment by user454322** [comment]
1.0.2 is available in macports.

See https://github.com/macports/macports-ports/pull/12036
