### ISSUE TITLE
install on High Sierra fails

### ISSUE THREAD

**Issue by LarryMartell** [user454322/realpath#2]
Trying to install on High Sierra:

$ sudo /opt/local/bin/port install realpath
--->  Fetching archive for realpath
--->  Attempting to fetch realpath-1.0.1_1.darwin_17.x86_64.tbz2 from https://packages.macports.org/realpath
--->  Attempting to fetch realpath-1.0.1_1.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/realpath
--->  Installing realpath @1.0.1_1
--->  Activating realpath @1.0.1_1
--->  Cleaning realpath
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  Found 10 broken ports, determining rebuild order
You can always run 'port rev-upgrade' again to fix errors.
The following ports will be rebuilt:
 blosc @1.5.2
 llvm-3.4 @3.4.2
 cctools @862+llvm34
 db48 @4.8.30
 py27-numexpr @2.4
 gettext @0.19.4
 pcre @8.36
 swig @3.0.5
 hdf5 @1.8.14+cxx
 zmq @3.2.5
Continue? [Y/n]: y
--->  Fetching archive for lz4
--->  Attempting to fetch lz4-1.9.3_1.darwin_17.x86_64.tbz2 from https://packages.macports.org/lz4
--->  Attempting to fetch lz4-1.9.3_1.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/lz4
--->  Installing lz4 @1.9.3_1
--->  Activating lz4 @1.9.3_1
--->  Cleaning lz4
--->  Fetching archive for zlib
--->  Attempting to fetch zlib-1.2.11_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/zlib
--->  Attempting to fetch zlib-1.2.11_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/zlib
--->  Installing zlib @1.2.11_0
--->  Cleaning zlib
--->  Deactivating zlib @1.2.8_0
--->  Cleaning zlib
--->  Activating zlib @1.2.11_0
--->  Cleaning zlib
--->  Fetching archive for libiconv
--->  Attempting to fetch libiconv-1.16_1.darwin_17.x86_64.tbz2 from https://packages.macports.org/libiconv
--->  Attempting to fetch libiconv-1.16_1.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/libiconv
--->  Installing libiconv @1.16_1
--->  Cleaning libiconv
--->  Deactivating libiconv @1.14_0
--->  Cleaning libiconv
--->  Activating libiconv @1.16_1
--->  Cleaning libiconv
--->  Fetching archive for ncurses
--->  Attempting to fetch ncurses-6.2_1.darwin_17.x86_64.tbz2 from https://packages.macports.org/ncurses
--->  Attempting to fetch ncurses-6.2_1.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/ncurses
--->  Installing ncurses @6.2_1
--->  Cleaning ncurses
--->  Deactivating ncurses @5.9_2
--->  Cleaning ncurses
--->  Activating ncurses @6.2_1
--->  Cleaning ncurses
--->  Computing dependencies for gettext
--->  Fetching archive for gettext
--->  Attempting to fetch gettext-0.19.8.1_2.darwin_17.x86_64.tbz2 from https://packages.macports.org/gettext
--->  Attempting to fetch gettext-0.19.8.1_2.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/gettext
--->  Installing gettext @0.19.8.1_2
--->  Cleaning gettext
--->  Computing dependencies for gettext
--->  Deactivating gettext @0.19.4_0
--->  Cleaning gettext
--->  Activating gettext @0.19.8.1_2
--->  Cleaning gettext
--->  Computing dependencies for xz
--->  Fetching archive for xz
--->  Attempting to fetch xz-5.2.5_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/xz
--->  Attempting to fetch xz-5.2.5_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/xz
--->  Installing xz @5.2.5_0
--->  Cleaning xz
--->  Computing dependencies for xz
--->  Deactivating xz @5.2.1_0
--->  Cleaning xz
--->  Activating xz @5.2.5_0
--->  Cleaning xz
--->  Computing dependencies for zstd
--->  Fetching archive for zstd
--->  Attempting to fetch zstd-1.5.0_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/zstd
--->  Attempting to fetch zstd-1.5.0_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/zstd
--->  Installing zstd @1.5.0_0
--->  Activating zstd @1.5.0_0
--->  Cleaning zstd
--->  Fetching archive for lzo2
--->  Attempting to fetch lzo2-2.10_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/lzo2
--->  Attempting to fetch lzo2-2.10_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/lzo2
--->  Installing lzo2 @2.10_0
--->  Cleaning lzo2
--->  Deactivating lzo2 @2.08_0
--->  Cleaning lzo2
--->  Activating lzo2 @2.10_0
--->  Cleaning lzo2
--->  Computing dependencies for snappy
--->  Fetching archive for snappy
--->  Attempting to fetch snappy-1.1.9_2.darwin_17.x86_64.tbz2 from https://packages.macports.org/snappy
--->  Attempting to fetch snappy-1.1.9_2.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/snappy
--->  Installing snappy @1.1.9_2
--->  Activating snappy @1.1.9_2
--->  Cleaning snappy
--->  Computing dependencies for blosc
--->  Fetching archive for blosc
--->  Attempting to fetch blosc-1.21.0_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/blosc
--->  Attempting to fetch blosc-1.21.0_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/blosc
--->  Installing blosc @1.21.0_0
--->  Cleaning blosc
--->  Computing dependencies for blosc
--->  Deactivating blosc @1.5.2_0
--->  Cleaning blosc
--->  Activating blosc @1.21.0_0
--->  Cleaning blosc
--->  Fetching archive for libffi
--->  Attempting to fetch libffi-3.3_1.darwin_17.x86_64.tbz2 from https://packages.macports.org/libffi
--->  Attempting to fetch libffi-3.3_1.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/libffi
--->  Installing libffi @3.3_1
--->  Cleaning libffi
--->  Deactivating libffi @3.2.1_0
--->  Cleaning libffi
--->  Activating libffi @3.3_1
--->  Cleaning libffi
--->  Fetching archive for db48
--->  Attempting to fetch db48-4.8.30_4.darwin_17.x86_64.tbz2 from https://packages.macports.org/db48
--->  Attempting to fetch db48-4.8.30_4.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/db48
--->  Unable to uninstall db48 @4.8.30_4, the following ports depend on it:
--->  	python27 @2.7.9_0
Warning: Uninstall forced.  Proceeding despite dependencies.
--->  Deactivating db48 @4.8.30_4
--->  Cleaning db48
--->  Uninstalling db48 @4.8.30_4
--->  Cleaning db48
--->  Installing db48 @4.8.30_4
--->  Activating db48 @4.8.30_4
--->  Cleaning db48
--->  Computing dependencies for readline
--->  Fetching archive for readline
--->  Attempting to fetch readline-8.1.000_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/readline
--->  Attempting to fetch readline-8.1.000_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/readline
--->  Installing readline @8.1.000_0
--->  Activating readline @8.1.000_0
--->  Cleaning readline
--->  Computing dependencies for gdbm
--->  Fetching archive for gdbm
--->  Attempting to fetch gdbm-1.19_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/gdbm
--->  Attempting to fetch gdbm-1.19_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/gdbm
--->  Installing gdbm @1.19_0
--->  Cleaning gdbm
--->  Computing dependencies for gdbm
--->  Deactivating gdbm @1.11_1
--->  Cleaning gdbm
--->  Activating gdbm @1.19_0
--->  Cleaning gdbm
--->  Computing dependencies for perl5.28
--->  Fetching archive for perl5.28
--->  Attempting to fetch perl5.28-5.28.3_2.darwin_17.x86_64.tbz2 from https://packages.macports.org/perl5.28
--->  Attempting to fetch perl5.28-5.28.3_2.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/perl5.28
--->  Installing perl5.28 @5.28.3_2
--->  Activating perl5.28 @5.28.3_2
--->  Cleaning perl5.28
--->  Computing dependencies for perl5
--->  Fetching archive for perl5
--->  Attempting to fetch perl5-5.28.3_0+perl5_28.darwin_17.noarch.tbz2 from https://packages.macports.org/perl5
--->  Attempting to fetch perl5-5.28.3_0+perl5_28.darwin_17.noarch.tbz2.rmd160 from https://packages.macports.org/perl5
--->  Installing perl5 @5.28.3_0+perl5_28
--->  Cleaning perl5
--->  Computing dependencies for perl5
--->  Deactivating perl5 @5.12.4_0+perl5_16
--->  Cleaning perl5
--->  Activating perl5 @5.28.3_0+perl5_28
--->  Cleaning perl5
--->  Fetching archive for llvm_select
--->  Attempting to fetch llvm_select-2_0.darwin_17.noarch.tbz2 from https://packages.macports.org/llvm_select
--->  Attempting to fetch llvm_select-2_0.darwin_17.noarch.tbz2.rmd160 from https://packages.macports.org/llvm_select
--->  Installing llvm_select @2_0
--->  Cleaning llvm_select
--->  Deactivating llvm_select @1.0_0
--->  Cleaning llvm_select
--->  Activating llvm_select @2_0
--->  Cleaning llvm_select
--->  Computing dependencies for llvm-3.4
--->  Fetching archive for llvm-3.4
--->  Attempting to fetch llvm-3.4-3.4.2_14.darwin_17.x86_64.tbz2 from https://packages.macports.org/llvm-3.4
--->  Attempting to fetch llvm-3.4-3.4.2_14.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/llvm-3.4
--->  Installing llvm-3.4 @3.4.2_14
--->  Cleaning llvm-3.4
--->  Computing dependencies for llvm-3.4
--->  Deactivating llvm-3.4 @3.4.2_6
--->  Cleaning llvm-3.4
--->  Activating llvm-3.4 @3.4.2_14
--->  Cleaning llvm-3.4
--->  Computing dependencies for libedit
--->  Fetching archive for libedit
--->  Attempting to fetch libedit-20210216-3.1_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/libedit
--->  Attempting to fetch libedit-20210216-3.1_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/libedit
--->  Installing libedit @20210216-3.1_0
--->  Cleaning libedit
--->  Computing dependencies for libedit
--->  Deactivating libedit @20140620-3.1_0
--->  Cleaning libedit
--->  Activating libedit @20210216-3.1_0
--->  Cleaning libedit
--->  Fetching archive for bzip2
--->  Attempting to fetch bzip2-1.0.8_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/bzip2
--->  Attempting to fetch bzip2-1.0.8_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/bzip2
--->  Installing bzip2 @1.0.8_0
--->  Cleaning bzip2
--->  Deactivating bzip2 @1.0.6_0
--->  Cleaning bzip2
--->  Activating bzip2 @1.0.8_0
--->  Cleaning bzip2
--->  Computing dependencies for openssl
--->  Fetching archive for openssl
--->  Attempting to fetch openssl-1.1.1k_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/openssl
--->  Attempting to fetch openssl-1.1.1k_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/openssl
--->  Installing openssl @1.1.1k_0
--->  Cleaning openssl
--->  Computing dependencies for openssl
--->  Deactivating openssl @1.0.2_0
--->  Cleaning openssl
--->  Activating openssl @1.1.1k_0
--->  Cleaning openssl
--->  Fetching archive for icu
--->  Attempting to fetch icu-67.1_4.darwin_17.x86_64.tbz2 from https://packages.macports.org/icu
--->  Attempting to fetch icu-67.1_4.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/icu
--->  Installing icu @67.1_4
--->  Activating icu @67.1_4
--->  Cleaning icu
--->  Computing dependencies for libxml2
--->  Fetching archive for libxml2
--->  Attempting to fetch libxml2-2.9.12_1.darwin_17.x86_64.tbz2 from https://packages.macports.org/libxml2
--->  Attempting to fetch libxml2-2.9.12_1.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/libxml2
--->  Installing libxml2 @2.9.12_1
--->  Cleaning libxml2
--->  Computing dependencies for libxml2
--->  Deactivating libxml2 @2.9.2_2
--->  Cleaning libxml2
--->  Activating libxml2 @2.9.12_1
--->  Cleaning libxml2
--->  Computing dependencies for xar
--->  Fetching archive for xar
--->  Attempting to fetch xar-1.8.0.452_0.darwin_17.x86_64.tbz2 from https://packages.macports.org/xar
--->  Attempting to fetch xar-1.8.0.452_0.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/xar
--->  Installing xar @1.8.0.452_0
--->  Activating xar @1.8.0.452_0
--->  Cleaning xar
--->  Fetching archive for libcxx
--->  Attempting to fetch libcxx-5.0.1_4.darwin_17.noarch.tbz2 from https://packages.macports.org/libcxx
--->  Attempting to fetch libcxx-5.0.1_4.darwin_17.noarch.tbz2.rmd160 from https://packages.macports.org/libcxx
--->  Installing libcxx @5.0.1_4
--->  Activating libcxx @5.0.1_4
--->  Cleaning libcxx
--->  Computing dependencies for llvm-10
--->  Fetching archive for llvm-10
--->  Attempting to fetch llvm-10-10.0.1_1.darwin_17.x86_64.tbz2 from https://packages.macports.org/llvm-10
--->  Attempting to fetch llvm-10-10.0.1_1.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/llvm-10
--->  Installing llvm-10 @10.0.1_1
--->  Activating llvm-10 @10.0.1_1
--->  Cleaning llvm-10
--->  Computing dependencies for cctools
--->  Fetching archive for cctools
--->  Attempting to fetch cctools-949.0.1_1+llvm10.darwin_17.x86_64.tbz2 from https://packages.macports.org/cctools
--->  Attempting to fetch cctools-949.0.1_1+llvm10.darwin_17.x86_64.tbz2.rmd160 from https://packages.macports.org/cctools
--->  Installing cctools @949.0.1_1+llvm10
--->  Cleaning cctools
--->  Computing dependencies for cctools
--->  Deactivating cctools @862_1+llvm34
--->  Cleaning cctools
--->  Activating cctools @949.0.1_1+llvm10
--->  Cleaning cctools
Error: rev-upgrade failed: invalid command name "::registry::entry4"
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.

**Comment by user454322** [comment]
This seems to be an issue with the broken ports, i.e., your ports system, not an issue with this particular port.

**Comment by user454322** [comment]
@LarryMartell Try fixing your ports, then try again installing realpath and reopen the ticket if you come across issues.
